### ISSUE TITLE
In a large-scale infrastructure, can I run jobs on a separate server?

### ISSUE THREAD

**Issue by theodorDiaconu** [msavin/SteveJobs...meteor.jobs.queue.schedule.background.tasks#27]
I want to have a dedicated server, or group of servers that run the jobs, you can say they are a separate microservice.

Are concurrency issues treated ?

How would that work ?

**Comment by msavin** [comment]
Here's how it works right now:

Each queue runs one job at a time, based on which job is due to run the soonest OR which job is due to run and has the highest priority. When one job is completed, the next one starts, until there are no more. Once there are no more, the package will ping the database every 30 seconds to see if the situation has changed.

If one wants to run the package on a separate server, I imagine they would need to set up a REST API and make calls to it. I suppose there are more clever ways that this could be done, especially if both servers are Meteor, but I haven't gone down that rabbit hole just yet.
